export const FETCH_AMORTIZATION_REQUEST = 'FETCH_AMORTIZATION_REQUEST';
export const FETCH_AMORTIZATION_SUCCESS = 'FETCH_AMORTIZATION_SUCCESS';
export const FETCH_AMORTIZATION_FAILURE = 'FETCH_AMORTIZATION_FAILURE';
